apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crate-web
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rodrigo-arcos/crate-web-argoCD.git
    targetRevision: HEAD
    path: manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace: kustomize
 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
