apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - nodePort: 31002
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: rodrigoarcos/frontend-jenkins:5
        imagePullPolicy: IfNotPresent
        name: frontend
        ports:
        - containerPort: 3000
